### ISSUE TITLE
Should samples mimic the specflow samples?

### ISSUE THREAD

**Issue by smudge202** [stajs/SpecFlow.NetCore#11]
Specifically, should the samples here mimic: https://github.com/techtalk/SpecFlow-Examples/tree/master/ASP.NET-MVC/BookShop but with `dnx451` / `dnx46`?

Note, we should probably ask the TechTalk guys if we decide to provide a DNX version of their samples.

**Comment by stajs** [comment]
My initial reaction is "whoa, that looks like a helluvalotta work", which roughly translates to "umm, no...?".

But srsly, I'm not sure we need to go in to that level of detail. I think it's enough if these samples show that glue files are generated from feature files, and leave the official examples to show more complex SpecFlow usage.

You could try chatting to the TechTalk guys, and happy to take a PR but seems like a lot of work for a hopefully short-lived project!

**Comment by smudge202** [comment]
I don't think it would be all that much work because we can almost copy/paste everything and then ""simply"" wire in dnx. However, I'm happy to skip it.

I'm not up to date on how the official repo is doing with regards to dnx compatibility, I should probably go do some research. Am I correct in thinking it will happen as part of their v2 work?

Maybe the effort would be better spent seeing what can be done to help them out.

**Comment by stajs** [comment]
Yeah, I think that's a better plan; at least the effort should be around longer than this project. I'm not 100% sure on what's in v2, but there is a separate repo for the extension that I've been meaning to investigate, but time...

Let me know what your research uncovers.

**Comment by smudge202** [comment]
Scanning over the issues, commits, branches, and `SpecFlow.VisualStudio` repo which I believe you were referring to, I basically got nowhere. I need to get home and test all the pieces together which will involve getting them to build and hooking up to the ci nuget feed. I'll let you know how I get on.

I've also hopped onto the google group and asked the v2.0 branch fella if he knows where we stand on DNX and what we can do to help. To be honest, the repo is a bit of a mess with regards to issue and roadmap management.

**Comment by stajs** [comment]
I don't think there is any appetite for this right now, so closing.
