### ISSUE TITLE
Support Scenario Outlines

### ISSUE THREAD

**Issue by bowman-jm** [stajs/SpecFlow.NetCore#12]
Specflow generator is trying to use Xunit.Extensions.TheoryAttribute and Xunit.Extensions.InlineDataAttribute, however these attributes have been rolled into the core Xunit namespace in 2.0, and Xunit.Extensions does not support DNX...

**Comment by bowman-jm** [comment]
I will submit a pull request for this fix

**Comment by bowman-jm** [comment]
#13

**Comment by stajs** [comment]
Thanks for the PR, I'll look to get an updated NuGet package soon.

**Comment by stajs** [comment]
Package up: https://www.nuget.org/packages/SpecFlow.Dnx/1.0.0-beta1

**Comment by smudge202** [comment]
Into betas. Exciting. :)

**Comment by stajs** [comment]
Yeah, wasn't _meant_ to be. I was intending to keep it alpha forever, [but... thanks NuGet](https://github.com/stajs/SpecFlow.Dnx/commit/22f7861d3335f00a32d7d74cf35f743befd1f590).

![image](https://cloud.githubusercontent.com/assets/2253814/11645518/ff013ce8-9db9-11e5-9fcc-587ff3b4fb96.png)

It meant that anyone specifying a `1.0.0-*` dependency wouldn't see `alpha10` :-1:

**Comment by smudge202** [comment]
Haha. I know your pain. When you're expecting more than 9 builds you need to use `1.0.0-alpha1-build*` (similar to xunit).

**Comment by stajs** [comment]
Samples and README updated.

**Comment by bowman-jm** [comment]
Thanks everyone!
