### ISSUE TITLE
Update samples for SpecFlow 2.0

### ISSUE THREAD

**Issue by stajs** [stajs/SpecFlow.NetCore#16]
See #15.

**Comment by erik-inkapool** [comment]
Is there a reason that this is open? I think the project has SpecFlow 2.0 support (for both dnx and rtm) or am I mistaken?

**Comment by smudge202** [comment]
I can confirm, 2.0+ has been working for a while.

**Comment by stajs** [comment]
Yeah, this is all good. I just need to tidy up the sample folder name and I'll probably drop support for anything but latest SpecFlow.
