### ISSUE TITLE
Tags don't generate traits

### ISSUE THREAD

**Issue by smudge202** [stajs/SpecFlow.NetCore#17]
I haven't diagnosed whether this is a result of the dnx integration or there's another cause yet.

To reproduce, follow the guide in the readme to get everything up and running (love that readme). Then add a "@tag" to a scenario and build for test discovery. If you group by traits in the test explorer you'll see all scenarios are listed without traits. Normally they'd have half a dozen such as the feature name.

**Comment by smudge202** [comment]
Never mind, caused by this: https://github.com/aspnet/Tooling/issues/182

I can see the trait attributes being generated as expected, it's simply that the VS tooling is no good. Looks like it won't be fixed for some time yet too...

**Comment by stajs** [comment]
Bummer. Hopefully it gets fixed soon!
