### ISSUE TITLE
Error with sample project of SpecFlow.Dnx and french localization

### ISSUE THREAD

**Issue by greg-hrv** [stajs/SpecFlow.NetCore#18]
Hi everyone !

I try to work with Specflow 2.0, localization and SpecFlow.Dnx with recommended configuration :

> https://github.com/stajs/SpecFlow.Dnx

For my sample, I use this project on SpecFlow.Dnx github :

> https://github.com/stajs/SpecFlow.Dnx/tree/master/samples/VS2015/SpecFlow%201.9.0/dnx46%201.0.0-rc1-final

By default, the project use default localization (en-US).
When I change the localization to french (fr-FR), I have an error :

> Folder\Folder.feature -> test generation failed

Here is my feature changed :

```
# language: fr-FR
Fonctionnalité: Feature in folder

Plan du scénario: SpecFlow glue files are generated
    Etant donné I am curious
    Quand I request the version
    Alors the result is constant
```

Here is my app.config with culture defined :

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <configSections>
        <section name="specFlow" type="TechTalk.SpecFlow.Configuration.ConfigurationSectionHandler, TechTalk.SpecFlow" />
    </configSections>
    <specFlow>
    <language feature="fr-FR" />
    <bindingCulture name="fr-FR" />
        <unitTestProvider name="xUnit" />
    </specFlow>
</configuration>
```

If this feature works in english (with english keyword of course), why it doesn't work in french ?
It seems there is an error with letters with accent.

I tried to debug specflow tools code, and I have an error at this line (class SpecFlowGherkinParser method Parse) :
`var feature = parser.Parse(new TokenScanner(featureFileReader), tokenMatcher);`

Thank you for your help.

Greg

**Comment by greg-hrv** [comment]
This is a bug with Gherkin parser.
See https://github.com/techtalk/SpecFlow/issues/582

**Comment by stajs** [comment]
Interesting, good luck!
