### ISSUE TITLE
Update readme for dotnetcore

### ISSUE THREAD

**Issue by erik-inkapool** [stajs/SpecFlow.NetCore#23]
The readme needs to be updated to cover for the dot net core tools configuration.

I may have time to do this during the week as there are only a few things that have changed. Otherwise I'll look into it during the weekend.

**Comment by stajs** [comment]
Cool. I might beat you to it; now that there is a package on nuget.org I'm keen to get it updated.

**Comment by stajs** [comment]
Remember to include note about the double-building bug #22.
