### ISSUE TITLE
Clarification of RTM project.json

### ISSUE THREAD

**Issue by smudge202** [stajs/SpecFlow.NetCore#24]
Currently, the `specflow.netcore` package only targets `NetCoreApp1.0`. However, the `specflow` package itself is not available in NetCoreApp's.

So, for example, these project.json's both fail:

``` json
{
  "dependencies": {
    "dotnet-test-xunit": "2.2.0-preview2-build1029",
    "specflow": "2.1.0",
    "specflow.netcore": "1.0.0-rc1",
    "xunit": "2.2.0-beta2-build3300"
  },
  "tools": {
    "dotnet-specflow": "1.0.0-rc1"
  },
  "testRunner": "xunit",
  "frameworks": {
    "net461": {}
  },
  "scripts": {
    "precompile": [ "dotnet specflow" ]
  }
}
```

_Fails because `specflow.netcore` does not support `net461`_.

``` json
{
  "dependencies": {
    "dotnet-test-xunit": "2.2.0-preview2-build1029",
    "specflow": "2.1.0",
    "specflow.netcore": "1.0.0-rc1",
    "xunit": "2.2.0-beta2-build3300"
  },
  "tools": {
    "dotnet-specflow": "1.0.0-rc1"
  },
  "testRunner": "xunit",
  "frameworks": {
    "netcoreapp1.0": {
      "dependencies": {
        "Microsoft.NETCore.App": {
          "type": "platform",
          "version": "1.0.0"
        }
      }
    }
  },
  "scripts": {
    "precompile": [ "dotnet specflow" ]
  }
}
```

_Fails because `specflow` does not support `netcoreapp`_.

Before the change to netcore, we could get this to work as follows:

``` json
{
  "dependencies": {
    "dotnet-test-xunit": "2.2.0-preview2-build1029",
    "specflow": "2.1.0",
    "specflow.dnx": "1.0.0-beta3",
    "xunit": "2.2.0-beta2-build3300"
  },
  "tools": {
    "dotnet-specflow": "1.0.0-beta3"
  },
  "testRunner": "xunit",
  "frameworks": {
    "net461": {}
  },
  "scripts": {
    "precompile": [ "dotnet specflow" ]
  }
}
```

_NB: I was using an internal build of @erik-lundgren's netcore migration at the time of the above._

Specflow itself doesn't actually specify targets on the NuGet page (I hate that), however you can see from the package itself that it only has a `net45` lib folder (therefore only available with the full .Net 4.5+). 

Whilst it would be nice for the main specflow package to get this all sorted, but the primary purpose of `specflow.dnx/netcore` is to provide a bridge in the interim. Therefore, I suspect what we want is to aim for something akin the last `project.json` I provided above? Perhaps @erik-lundgren can comment?

**Comment by smudge202** [comment]
I'll add, I'm utterly baffled right now as to why the official specflow.netcore package is failing when the custom build one worked. I can see the project.json's are similar enough that it should work (you don't need the stuff in `backup___` - version control mitigates the needs for commented out code!!). Both the internal build and the official build appear to target `netcoreapp1.0`, but I have literally two windows here whereby one package works, the other does not:
![specflow-netcore-01](https://cloud.githubusercontent.com/assets/2247869/18081698/52fa20a8-6e93-11e6-88b3-497d9f5da7ac.png)

**Comment by stajs** [comment]
I've just updated the sample, does that work for you? I think you might have been caught by a sneaky renaming on my part:

``` json
"tools": {
    "SpecFlow.NetCore": "1.0.0-rc2"
},

"scripts": {
    "precompile": [ "dotnet SpecFlow.NetCore" ]
}
```

Re: version control; yah, it was just a visual reminder more than anything.

---

`SpecFlow 2.1.0` requires full .NET Framework, so that's why the sample is `net461`. However it seems that you can't have a `tool` in the `project.json` unless you are `netcoreapp1.0`. I wanted the tool to take a dependency on SpecFlow but currently it doesn't look possible. I was going to do some research about this later to verify my understanding and possibly raise an issue (seems buggy to me).

ATM it seems to work okay because it looks like the monikers for the `tools` and `dependencies` can be different. Ideally SpecFlow release a `netcoreapp1.0` package soon.

**Comment by stajs** [comment]
Actually, just noted this as well (just talking about different monikers): you need to remove the dependency and just have it as a tool:

![image](https://cloud.githubusercontent.com/assets/2253814/18084509/a8719512-6efb-11e6-8e95-2fb8be102ae9.png)

I'm not sure how the tool `dotnet-specflow` is being resolved. At first I thought it could be being pulled from the package cache from when you installed @erik-lundgren's build, but it doesn't make sense unless he had a `1.0.0-rc1` version.

**Comment by smudge202** [comment]
Ok, yeh, I managed to get this working. Removing the dependency and only listing it as a tool prevents the compilation issue, however, can someone confirm (struggling for time) that if I hadn't listed the package as a dependency and therefore pulled the package down already, then it wouldn't have resolved? (i.e. it would work in samples project of this repo because VS can resolve the project and doesn't need to look on NuGet, for other solutions it needs to pull the package down from NuGet).

I only ask because when I change the text in the tools section, I don't see any output with regards to a NuGet get, like you would if you changed something in the dependencies section.

In addition, the tools section is CASE-SENSITIVE. If the case doesn't match exactly, you'll receive this error on build:

`C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Common.Targets(262,5): error : No executable found matching command "dotnet-SpecFlow.NetCore"`

However, the project build status will still be:

```
Compilation succeeded.
1>      0 Warning(s)
1>      0 Error(s)
1>  Time elapsed 00:00:01.0896462
```

(despite the above error in the output).

**Comment by stajs** [comment]
Confirm the tool is pulled down without being referenced as a dependency.

> it would work in samples project of this repo because VS can resolve the project and doesn't need to look on NuGet

I don't think VS can resolve the project. There isn't a project reference between `samples` and `src` and they are sibling folders not parent/child in case of any backtracking going on, and the package is pulled down by NuGet.
1. Deleted cached folders:
   - `%userprofile%\.nuget\packages\.tools\SpecFlow.NetCore`
   - `%userprofile%\.nuget\packages\SpecFlow.NetCore`
2. Cloned fresh from latest master (d469ab87be0b562c6cba3b970f8fc38f26864a85 at time of writing).
3. Opening the Sample solution, `Output > Package Manager`:
   
   ```
   PATH=%PATH%
   C:\Program Files\dotnet\dotnet.exe restore "C:\GitHub\stajs\SpecFlow.NetCore\samples\VS2015\SpecFlow 2.1.0\net461\.vs\restore.dg"
   log  : Restoring packages for C:\GitHub\stajs\SpecFlow.NetCore\samples\VS2015\SpecFlow 2.1.0\net461\Sample.Website\project.json...
   log  : Restoring packages for C:\GitHub\stajs\SpecFlow.NetCore\samples\VS2015\SpecFlow 2.1.0\net461\Sample.Website.Tests\project.json...
   log  : Writing lock file to disk. Path: C:\GitHub\stajs\SpecFlow.NetCore\samples\VS2015\SpecFlow 2.1.0\net461\Sample.Website\project.lock.json
   log  : C:\GitHub\stajs\SpecFlow.NetCore\samples\VS2015\SpecFlow 2.1.0\net461\Sample.Website\Sample.Website.xproj
   log  : Restore completed in 1434ms.
   log  : Restoring packages for tool 'SpecFlow.NetCore' in C:\GitHub\stajs\SpecFlow.NetCore\samples\VS2015\SpecFlow 2.1.0\net461\Sample.Website.Tests\project.json...
   log  : Installing SpecFlow.NetCore 1.0.0-rc2.
   log  : Writing lock file to disk. Path: C:\GitHub\stajs\SpecFlow.NetCore\samples\VS2015\SpecFlow 2.1.0\net461\Sample.Website.Tests\project.lock.json
   log  : C:\GitHub\stajs\SpecFlow.NetCore\samples\VS2015\SpecFlow 2.1.0\net461\Sample.Website.Tests\Sample.Website.Tests.xproj
   log  : Restore completed in 5835ms.
   ```
4. New cached folders:
   - `%userprofile%\.nuget\packages\SpecFlow.NetCore\1.0.0-rc2`
   - `%userprofile%\.nuget\packages\.tools\SpecFlow.NetCore\1.0.0-rc2`

---

Re: case sensitive; That's annoying. :sob:

**Comment by stajs** [comment]
So I haven't paid much attention to the expanded declaration of `dependencies`, e.g.:

``` json
"dependencies": {
    "Microsoft.NETCore.App": {
        "type": "platform",
        "version": "1.0.0"
    }
}
```

But I've just noticed that EF tools do this:

``` json
"dependencies": {
    "Microsoft.EntityFrameworkCore.Tools": {
        "version": "1.0.0-preview2-final",
        "type": "build"
    }
},

"tools": {
    "Microsoft.EntityFrameworkCore.Tools": "1.0.0-preview2-final"
},
```
