### ISSUE TITLE
Restore "Test is pending" message

### ISSUE THREAD

**Issue by erik-inkapool** [stajs/SpecFlow.NetCore#27]
When adding a new test step there's no longer the "nice" output with the "Test pending" and the example code missing, rather there's an error related to nunit.framework

To reproduce just add a step to the "Specflow glue files are generated" tests like `And temp`, build and run the tests. the error is something like `Could not load file or assembly 'nunit.framework' or one of its dependencies`.

Some googling makes me believe this crops up if the SpecFlow config isn't explicitly set to use a specific framework.

First step to get back would be to add support for xunit, but as dotnet core now also supports mstest maybe we should try to also support that (I don't know of any other test frameworks). What's your opinion, as this package is only here until specflow releases their official stuff?

**Comment by erik-inkapool** [comment]
It does show up during execution if you run dotnet test from console, though. Right above the exception

**Comment by stajs** [comment]
Hmm, didn't notice that. Thanks for picking that up. I'll try and have a look tonight.

I'm not particularly motivated for mstest right now, but happy if someone wants to look at it.

**Comment by stajs** [comment]
Okay, I have no idea what is going on here. This was working for SpecFlow v1.9, but it looks like SpecFlow is now falling back to its default of NUnit for generating missing step definitions and then failing to load the assembly.

AFAICT, the generated `app.config` is correct. If you change:

``` xml
<unitTestProvider name="xUnit" />
```

... to:

``` xml
<unitTestProvider name="foo" />
```

...you'll get:

```
Interface cannot be resolved: TechTalk.SpecFlow.Generator.UnitTestProvider.IUnitTestGeneratorProvider('foo')
```

So it's recognizing the provider, it's just ignoring it.

**Comment by erik-inkapool** [comment]
When exactly do you get that? During specflow fix build?

I've been experimenting with changing the app.config in the output bin directory and that doesn't seem to matter at all, if I remember correctly. I'll try to verify this later.

**Comment by stajs** [comment]
Yes, during a build. Furthermore, using `xunit`, the generated glue files have xUnit attributes; using `nunit`, they have NUnit attributes, so the generation looks correct to me.

**Comment by stajs** [comment]
Maybe it's not the move from SpecFlow 1.9.0 to 2.1.0. I just tried downgrading to 1.9.0 and it still complained...

**Comment by erik-inkapool** [comment]
I think it might be some kind of runtime related stuff, I don't think the .dll.config file gets read for some reason. I don't think it has anything to do with our tool, because we're way out of the picture when the user is running the tests. perhaps this is dotnet cli related too? I've been scouring their issues pages but haven't found something like this there. Maybe I'll add one there, unless you think the issue is with us?

**Comment by stajs** [comment]
I wonder if it is the test runner...?

**Comment by stajs** [comment]
Actually, no, that was just clutching for straws. Ignore that.

**Comment by stajs** [comment]
Think I've found a smoking gun: if I change the [default provider](https://github.com/techtalk/SpecFlow/blob/396e0e40ca06e68c01a4ca46fa0dfc9fbbb5a8c3/TechTalk.SpecFlow/PlatformSpecific/ConfigDefaults.cs#L11), it works.

**Comment by stajs** [comment]
Found it. Debugging into SpecFlow, I can see it [tries to load the `specFlow` config section via `ConfigurationManager`](https://github.com/techtalk/SpecFlow/blob/396e0e40ca06e68c01a4ca46fa0dfc9fbbb5a8c3/TechTalk.SpecFlow/PlatformSpecific/RuntimeConfiguration.cs#L73). This is failing (returns `null`), so it never loads the configuration and therefore doesn't [set the provider name](https://github.com/techtalk/SpecFlow/blob/396e0e40ca06e68c01a4ca46fa0dfc9fbbb5a8c3/TechTalk.SpecFlow/PlatformSpecific/RuntimeConfiguration.cs#L122). Checking `AppDomain.CurrentDomain.SetupInformation.ConfigurationFile` shows it is trying to read from the test runner config: `dotnet-test-xunit.exe.Config`. Adding the required SpecFlow sections to the config, and the skeleton bindings are shown again in the test output:

![image](https://cloud.githubusercontent.com/assets/2253814/18230583/ee8273c2-72f3-11e6-9d28-9b651b2b0a70.png)

I'm not sure of the best way to fix this. I don't really want to start munging the runner config. @BradWilson do you have any advice on this?

**Comment by erik-inkapool** [comment]
Wow, nice find! 

I agree adding sections to the `dotnet-test-xunit` config doesn't seem like a neat solution, but I'll probably still use it for my project as this feature is pretty important to my workflow along with the `Context.Pending();`, which also breaks due to this issue. If I put that in, would you like a PR or should I keep it to myself?

**Comment by stajs** [comment]
I'll take a PR for it now to get it back in the short term, and potentially remove it later pending advice from @BradWilson.

**Comment by bradwilson** [comment]
That's only going to help desktop CLR; there are no config files built into .NET Core.

**Comment by stajs** [comment]
That's okay for now, AFAIK SpecFlow hasn't released a CoreCLR package yet.

**Comment by bradwilson** [comment]
We have added support for app domains (which is the source of your config issue) to `dotnet-test-xunit`, though it's as yet unreleased (part of the planned 2.2 beta 3 release).

**Comment by stajs** [comment]
Do you have any CI builds we could use?

**Comment by smudge202** [comment]
I'd assume here:  https://myget.org/gallery/xunit

**Comment by stajs** [comment]
I tried the latest builds. TBH I'm not sure how the runner is working; it outputs the skeleton from the command line still but not in VS Test Explorer. But I'm also not sure what build combinations are meant to be used together (xunit/runner).

**Comment by smudge202** [comment]
Iirc you can find Brad in various slack chats if you want to dig into it.

**Comment by bradwilson** [comment]
I'm not really familiar with what you're trying to accomplish, so maybe a branch to look at would be helpful. :)

**Comment by stajs** [comment]
Good idea. I'll try and assume no prior knowledge and restate the problem.

SpecFlow takes plain-English "feature" specifications and auto-generates "glue" files that link to your C# "step definitions". When this tool (then called `SpecFlow.Dnx`) was created, SpecFlow didn't have support for DNX or xUnit 2, so the tool patched support by:
1. Generating an `app.config` with the required `specFlow` section so that the glue files are generated mostly right for xUnit, then
2. Updating the generated glue files to use the right xUnit 2 attributes.

At one point in time (4ae594e56bfb145d05e861367ba422749d5575b7), the dependencies looked like this for the sample:

``` json
"dependencies": {
    "Sample.Website": "1.0.0-*",
    "SpecFlow": "1.9.0",
    "SpecFlow.Dnx": "1.0.0-beta1",
    "xunit": "2.1.0",
    "xunit.abstractions": "2.0.0",
    "xunit.assert": "2.1.0",
    "xunit.core": "2.1.0",
    "xunit.extensibility.core": "2.1.0",
    "xunit.extensibility.execution": "2.1.0",
    "xunit.runner.dnx": "2.1.0-rc1-build204",
    "xunit.runner.visualstudio": "2.1.0"
},
```

(Aside: Seeing `xunit.runner.visualstudio`, I wondered if that was the missing thing that made it work previously. However, [`dotnet-test-xunit`](https://myget.org/feed/xunit/package/nuget/dotnet-test-xunit) says it is both the Console and Visual Studio runner now.)

The [README at the time](https://github.com/stajs/SpecFlow.NetCore/blob/4ae594e56bfb145d05e861367ba422749d5575b7/README.md#generating-step-definitions) shows that for a feature with missing step definitions (i.e. you haven't written C# test code that implement your specification), when the test is run, the test output in Visual Studio will show skeleton step definitions (provided by SpecFlow) that you can copy-n-paste to get you started. This is a boon for your workflow:

![image](https://cloud.githubusercontent.com/assets/2253814/11574057/54f43bb8-9a6e-11e5-91d4-2910c1ee8185.png)

Moving from DNX to .NET Core, the integration between SpecFlow and the xUnit runner has broken. I trimmed down [a branch for a minimal reproduction](https://github.com/stajs/SpecFlow.NetCore/tree/issue-27/samples/VS2015/SpecFlow%202.1.0/net461) with these dependencies:

``` json
"dependencies": {
    "SpecFlow": "2.1.0",
    "xunit": "2.2.0-beta2-build3300",
    "dotnet-test-xunit": "2.2.0-preview2-build1029"
},
```

Now running a test with missing step definitions for xUnit results in a puzzling exception message for NUnit!

![image](https://cloud.githubusercontent.com/assets/2253814/18268831/a1a73e70-7479-11e6-9240-9b614d04fda2.png)

To [quote myself from above](https://github.com/stajs/SpecFlow.NetCore/issues/27#issuecomment-244596958):

> Debugging into SpecFlow, I can see it [tries to load the `specFlow` config section via `ConfigurationManager`](https://github.com/techtalk/SpecFlow/blob/396e0e40ca06e68c01a4ca46fa0dfc9fbbb5a8c3/TechTalk.SpecFlow/PlatformSpecific/RuntimeConfiguration.cs#L73). This is failing (returns `null`), so it never loads the configuration and therefore doesn't [set the provider name](https://github.com/techtalk/SpecFlow/blob/396e0e40ca06e68c01a4ca46fa0dfc9fbbb5a8c3/TechTalk.SpecFlow/PlatformSpecific/RuntimeConfiguration.cs#L122). Checking `AppDomain.CurrentDomain.SetupInformation.ConfigurationFile` shows it is trying to read from the test runner config: `dotnet-test-xunit.exe.Config`. Adding the required SpecFlow sections to the config, and the skeleton bindings are shown again in the test output:
> 
> ![image](https://cloud.githubusercontent.com/assets/2253814/18230583/ee8273c2-72f3-11e6-9d28-9b651b2b0a70.png)

`dotnet test` from Console does at least show skeletons for each missing step (although the VS output will show an entire class skeleton rather than individual method skeletons):

```
xUnit.net .NET CLI test runner (64-bit Desktop .NET win10-x64)
  Discovering: Sample.Website.Tests
  Discovered:  Sample.Website.Tests
  Starting:    Sample.Website.Tests
Given I don't have step definitions
-> No matching step definition found for the step. Use the following code to create one:
        [Given(@"I don't have step definitions")]
public void GivenIDonTHaveStepDefinitions()
{
    ScenarioContext.Current.Pending();
}
When I run the test
-> No matching step definition found for the step. Use the following code to create one:
        [When(@"I run the test")]
public void WhenIRunTheTest()
{
    ScenarioContext.Current.Pending();
}
Then the step definition skeletons are provided in the test output
-> No matching step definition found for the step. Use the following code to create one:
        [Then(@"the step definition skeletons are provided in the test output")]
public void ThenTheStepDefinitionSkeletonsAreProvidedInTheTestOutput()
{
    ScenarioContext.Current.Pending();
}
    Step definition skeletons are provided [FAIL]
      System.IO.FileNotFoundException : Could not load file or assembly 'nunit.framework' or one of its dependencies. The system cannot find the file specified.
```

I hope this helps with understanding the problem, and I haven't just confused it further. @BradWilson you said there was support for app domains which might fix this - could you point me to a particular build I could try out (and advise which versions of the runner/xunit should be used)?

**Comment by bradwilson** [comment]
The CI builds (available on [MyGet](https://myget.org/gallery/xunit)) include app domain support for `dotnet-test-xunit` when running against the desktop CLR (that is, target framework on `net4x`). Like all other runners for xUnit.net, app domains are turned on by default in this scenario.

Assuming that your `App.config` files are showing up correctly as `DllName.dll.config` in your `bin` folder, then `ConfigurationManager` should be able to pick them up. This should work both inside Visual Studio as well as from the command line.

**Comment by stajs** [comment]
I updated the [branch](https://github.com/stajs/SpecFlow.NetCore/tree/issue-27/samples/VS2015/SpecFlow%202.1.0/net461) to use the latest CI builds (0581570dbae4ced210eda98db36aa683ca97c202):

``` json
"dependencies": {
    "SpecFlow": "2.1.0",
    "xunit": "2.2.0-beta3-build3350",
    "dotnet-test-xunit": "2.2.0-preview3-build1045"
},
```

I have verified that `Sample.Website.Tests\app.config`:

``` xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <configSections>
        <section name="specFlow" type="TechTalk.SpecFlow.Configuration.ConfigurationSectionHandler, TechTalk.SpecFlow" />
    </configSections>
    <specFlow>
        <unitTestProvider name="xUnit" />
    </specFlow>
</configuration>
```

... is output to `Sample.Website.Tests\bin\Debug\net461\win7-x64\Sample.Website.Tests.dll.config`:

``` xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <configSections>
    <section name="specFlow" type="TechTalk.SpecFlow.Configuration.ConfigurationSectionHandler, TechTalk.SpecFlow" />
  </configSections>
  <specFlow>
    <unitTestProvider name="xUnit" />
  </specFlow>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" culture="neutral" />
        <bindingRedirect oldVersion="6.0.0.0" newVersion="9.0.0.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>
```

... next to `Sample.Website.Tests\bin\Debug\net461\win7-x64\Sample.Website.Tests.dll`.

The good news: from the command line, the output now includes a full class skeleton and more importantly, no mention of NUnit:

```
xUnit.net .NET CLI test runner (64-bit Desktop .NET win81-x64)
  Discovering: Sample.Website.Tests
  Discovered:  Sample.Website.Tests
  Starting:    Sample.Website.Tests
Given I don't have step definitions
-> No matching step definition found for the step. Use the following code to create one:
        [Given(@"I don't have step definitions")]
public void GivenIDonTHaveStepDefinitions()
{
    ScenarioContext.Current.Pending();
}
When I run the test
-> No matching step definition found for the step. Use the following code to create one:
        [When(@"I run the test")]
public void WhenIRunTheTest()
{
    ScenarioContext.Current.Pending();
}
Then the step definition skeletons are provided in the test output
-> No matching step definition found for the step. Use the following code to create one:
        [Then(@"the step definition skeletons are provided in the test output")]
public void ThenTheStepDefinitionSkeletonsAreProvidedInTheTestOutput()
{
    ScenarioContext.Current.Pending();
}
    Step definition skeletons are provided [FAIL]
      TechTalk.SpecFlow.SpecFlowException : Test pending: No matching step definition found for one or more steps.
      using System;
using TechTalk.SpecFlow;
namespace MyNamespace
{
    [Binding]
    public class StepDefinitions
    {
        [Given(@"I don't have step definitions")]
public void GivenIDonTHaveStepDefinitions()
{
    ScenarioContext.Current.Pending();
}
              [When(@"I run the test")]
public void WhenIRunTheTest()
{
    ScenarioContext.Current.Pending();
}
              [Then(@"the step definition skeletons are provided in the test output")]
public void ThenTheStepDefinitionSkeletonsAreProvidedInTheTestOutput()
{
    ScenarioContext.Current.Pending();
}
    }
}
      Stack Trace:
           at TechTalk.SpecFlow.UnitTestProvider.XUnitRuntimeProvider.TestPending(String message)
           at SpecFlow.GeneratedTests.Issue27Feature.ScenarioCleanup()
        Root.feature(6,0): at SpecFlow.GeneratedTests.Issue27Feature.StepDefinitionSkeletonsAreProvided()
  Finished:    Sample.Website.Tests
=== TEST EXECUTION SUMMARY ===
   Sample.Website.Tests  Total: 1, Errors: 0, Failed: 1, Skipped: 0, Time: 0.615s
SUMMARY: Total: 1 targets, Passed: 0, Failed: 1.
```

The bad news: Visual Studio doesn't find any tests when building:

```
------ Discover test started ------
========== Discover test finished: 0 found (0:00:00.0250151) ==========
------ Discover test started ------
Discovering tests in 'C:\GitHub\stajs\SpecFlow.NetCore\samples\VS2015\SpecFlow 2.1.0\net461\Sample.Website.Tests\project.json' ["C:\Program Files\dotnet\dotnet.exe" test "C:\GitHub\stajs\SpecFlow.NetCore\samples\VS2015\SpecFlow 2.1.0\net461\Sample.Website.Tests\project.json" --output "C:\GitHub\stajs\SpecFlow.NetCore\samples\VS2015\SpecFlow 2.1.0\net461\Sample.Website.Tests\bin\Debug\net461\win7-x64" --port 46971 --parentProcessId 14712 --no-build]
========== Discover test finished: 0 found (0:00:01.2060829) ==========
```

**Comment by stajs** [comment]
I think the runner has a regression bug. I created a smaller repro removing SpecFlow from the equation, and [wound the runner version back](https://github.com/stajs/xunit-config/blob/214af5720102a190b0c91e1ba1ac79bcaec2fbd9/Xunit.Config/src/Xunit.Config.Net461/project.json) until I found a version that had output in Visual Studio Test Explorer:

``` json
"dependencies": {
    "xunit": "2.2.0-beta3-build3350",
    "dotnet-test-xunit": "2.2.0-preview3-build1030"
},

```

So [given a test like this](https://github.com/stajs/xunit-config/blob/10b9a6ce263a01523e7f82ac371ad329aa7bc35a/Xunit.Config/src/Xunit.Config.Net461/ConfigurationManagerTests.cs):

``` csharp
[Fact]
public void CanReadAppConfig()
{
    WriteLine("AppDomain.CurrentDomain.SetupInformation.ConfigurationFile: " + AppDomain.CurrentDomain.SetupInformation.ConfigurationFile);
    var appSettings = ConfigurationManager.AppSettings;
    WriteLine("appSettings: " + (appSettings == null ? "null" : "not null"));
    WriteLine("appSettings[\"Foo\"]: " + appSettings["Foo"]);
    Assert.NotNull(ConfigurationManager.AppSettings);
    Assert.Equal("Bar", appSettings["Foo"]);
}
```

... both Visual Studio and console fails (I assume because the app domain stuff isn't in yet but at least they are consistent):

![image](https://cloud.githubusercontent.com/assets/2253814/18346068/91ff3f6e-7612-11e6-9db9-90443c648349.png)

```
xUnit.net .NET CLI test runner (64-bit Desktop .NET win10-x64)
  Discovering: Xunit.Config.Net461
  Discovered:  Xunit.Config.Net461
  Starting:    Xunit.Config.Net461
AppDomain.CurrentDomain.SetupInformation.ConfigurationFile: G:\Git\stajs\xunit-config\Xunit.Config\src\Xunit.Config.Net461\bin\Debug\net461\win7-x64\dotnet-test-xunit.exe.Config
appSettings: not null
appSettings["Foo"]:
    Xunit.Config.Net461.ConfigurationManagerTests.CanReadAppConfig [FAIL]
      Assert.Equal() Failure
      Expected: Bar
      Actual:   (null)
  Finished:    Xunit.Config.Net461
```

_Note:_ It is trying to read from `dotnet-test-xunit.exe.Config`.

[Using the latest runner](https://github.com/stajs/xunit-config/blob/e70315e6ac5ad92fb4d15b1a22c943473fdb0168/Xunit.Config/src/Xunit.Config.Net461/project.json) (at time of writing `-build1045`), Visual Studio doesn't find any tests but the console is now working as expected:

```
------ Discover test started ------
Discovering tests in 'G:\Git\stajs\xunit-config\Xunit.Config\src\Xunit.Config.Net461\project.json' ["C:\Program Files\dotnet\dotnet.exe" test "G:\Git\stajs\xunit-config\Xunit.Config\src\Xunit.Config.Net461\project.json" --output "G:\Git\stajs\xunit-config\Xunit.Config\src\Xunit.Config.Net461\bin\Debug\net461\win7-x64" --port 49994 --parentProcessId 14956 --no-build]
========== Discover test finished: 0 found (0:00:01.5282451) ==========
```

```
xUnit.net .NET CLI test runner (64-bit Desktop .NET win10-x64)
  Discovering: Xunit.Config.Net461
  Discovered:  Xunit.Config.Net461
  Starting:    Xunit.Config.Net461
AppDomain.CurrentDomain.SetupInformation.ConfigurationFile: G:\Git\stajs\xunit-config\Xunit.Config\src\Xunit.Config.Net461\bin\Debug\net461\win7-x64\Xunit.Config.Net461.dll.config
appSettings: not null
appSettings["Foo"]: Bar
  Finished:    Xunit.Config.Net461
```

_Note:_ It has now found the right config: `Xunit.Config.Net461.dll.config`.

Given [the warning](https://xunit.github.io/docs/getting-started-dotnet-core.html) about unsupported versions probably applies to CI builds as well, @BradWilson can you advise if I should file a bug for xUnit, or would you rather I didn't add noise while you are working on this.

**Comment by stajs** [comment]
**This is all conjecture!** I don't know anything about how test discovery works, but I found [an issue that looks related](https://github.com/xunit/xunit/issues/934) to my untrained eye.

### -build1045

Starting with the latest runner version, if I just use `--list` it discovers the test:

```
>dotnet-test-xunit.exe Xunit.Config.Net461.dll --list
xUnit.net .NET CLI test runner (64-bit Desktop .NET win10-x64)
  Discovering: Xunit.Config.Net461
Xunit.Config.Net461.ConfigurationManagerTests.CanReadAppConfig
```

**Massive assumption:** Visual Studio uses `--designtime`. Adding that doesn't find any tests.

```
>dotnet-test-xunit.exe Xunit.Config.Net461.dll --list --designtime
xUnit.net .NET CLI test runner (64-bit Desktop .NET win10-x64)
  Discovering: Xunit.Config.Net461
{"MessageType":"TestRunner.TestCompleted","Payload":null}
```

### -build1030

Rewinding the runner back, `--designtime` finds the test! In my mind that explains why Test Explorer shows the test for the older runner version.

```
>dotnet-test-xunit.exe Xunit.Config.Net461.dll --list --designtime
xUnit.net .NET CLI test runner (64-bit Desktop .NET win10-x64)
  Discovering: Xunit.Config.Net461
{"MessageType":"TestDiscovery.TestFound","Payload":{"CodeFilePath":"G:\\Git\\stajs\\xunit-config\\Xunit.Config\\src\\Xunit.Config.Net461\\ConfigurationManagerTests.cs","DisplayName":"Xunit.Config.Net461.ConfigurationManagerTests.CanReadAppConfig","FullyQualifiedName":"Xunit.Config.Net461.ConfigurationManagerTests.CanReadAppConfig","Id":"c61720d6-5bfd-db85-4a50-3a10fa896156","LineNumber":11,"Properties":{}}}
Xunit.Config.Net461.ConfigurationManagerTests.CanReadAppConfig
{"MessageType":"TestRunner.TestCompleted","Payload":null}
```

**Comment by smudge202** [comment]
Enjoying your exploration of xUnit and the Test Runner? I did a similar exercise last year, Brad kindly gave me a tonne of helpful info in Slack. I don't remember enough to help here, but you could probably submodule xunit in and debug the difference?

**Comment by stajs** [comment]
I enjoy exploring, but I never have enough time to explore as much as I want. Also, it can be fun getting lost every now and then! On my next opportunity for exploring, I might debug further...

**Comment by stajs** [comment]
I haven't yet had a chance to investigate further. There are some [newer builds available](https://myget.org/feed/xunit/package/nuget/xunit), however I don't expect they will work until [the upstream bug](https://github.com/xunit/xunit/issues/934) is fixed.

**Comment by erik-am** [comment]
I can confirm the issue as well, it was driving me nuts! Good to know that it only occurs when you're missing/pending step definitions, first I was afraid that the tests wouldn't run correctly at all

**Comment by stajs** [comment]
https://github.com/stajs/SpecFlow.NetCore/issues/85#issuecomment-550567940
