### ISSUE TITLE
Consolidate formatting settings

### ISSUE THREAD

**Issue by smudge202** [stajs/SpecFlow.NetCore#29]
As per discussion on #28 and a previous PR, can we do something regarding formatting. Personally I recommend an `.editorconfig` approach, which requires a small extension be installed to VS (though works natively in VSCode).

The extension is here: https://visualstudiogallery.msdn.microsoft.com/c8bccfe2-650c-4b42-bc5c-845e21f96328

Once installed, simply add an editorconfig file as per the description on that page to have everyone share the format settings. (Personally I prefer to Keep Tabs with a tab space of 4 for c#, but it doesn't matter so long as solution level settings are shared).

**Comment by stajs** [comment]
I prefer Tabs (size = 3 spaces).

**Comment by stajs** [comment]
Wasn't meaning that to sound dictatorial; I was hoping that if it keeps Tabs, that personal preference could still be used on what the sizing is but I'm not sure.

**Comment by smudge202** [comment]
Yup, that's the beauty of using tabs, we can use our own tab size. :smile:

**Comment by stajs** [comment]
Let me know if it works for you.
