### ISSUE TITLE
Generate Step Definitions

### ISSUE THREAD

**Issue by smudge202** [stajs/SpecFlow.NetCore#3]
I'm not sure of the best way to face this and appreciate that the project itself is (hopefully) just a workaround pending better support from the specflow VS extension.

I've only used specflow for a month or two now, and would typically copy the step definitions for a given feature to the clipboard and paste them in my choice of step file. As far as I can tell, this isn't possible within a DNX project using this workaround.

How do you achieve this currently, @stajs ? More to the point, is there a way to workaround the step definition issue? The only thing I can think of is if `SpecFlow.Dnx` is able to consume additional command(s) for step definition generation? One possible solution would be to hijack the clipboard during build (copy any undefined steps to clipboard)? 

I know that's not ideal but struggling to think of a good workaround.

**Comment by stajs** [comment]
It's _kind_ of possible, but definitely not as nice as the typical usage from the extension.

This is what I've been doing (I should probably also add this to the README).

So, a feature file:

![image](https://cloud.githubusercontent.com/assets/2253814/11574021/299d6d40-9a6e-11e5-9342-3cf9c91565cc.png)

Build to generate the `.cs` file and run it:

![image](https://cloud.githubusercontent.com/assets/2253814/11574057/54f43bb8-9a6e-11e5-91d4-2910c1ee8185.png)

Copy All:

![image](https://cloud.githubusercontent.com/assets/2253814/11574068/66050a5e-9a6e-11e5-9f7a-264c6935b3b6.png)

Paste in Notepad++, then copy out the actual steps:

![image](https://cloud.githubusercontent.com/assets/2253814/11574120/932672c0-9a6e-11e5-8f70-cff5a74c5da6.png)

Given this should be a short-lived solution, this workaround might be enough.

**Comment by stajs** [comment]
I've updated the README.

**Comment by smudge202** [comment]
Perfect. I'll merge your changes (grumble) and then add my PR.

**Comment by stajs** [comment]
Ah, sorry to conflict you, didn't expect you to be that quick!

**Comment by smudge202** [comment]
Lol, no worries. It auto-merged.
