### ISSUE TITLE
Other test frameworks

### ISSUE THREAD

**Issue by smudge202** [stajs/SpecFlow.NetCore#30]
Was just reading through the README updates (GJ :+1:), noticed that we still state:

> however (at time of writing) no other test frameworks are available for .NET Core.

This is no longer true, MsTest has been available [since RC2](https://blogs.msdn.microsoft.com/visualstudioalm/2016/05/30/announcing-mstest-framework-support-for-net-core-rc2-asp-net-core-rc2/).

We should probably test if an app.config change is enough to make things work as intended. Docs may also need updating to reflect the two frameworks, perhaps even allow a command line arg to be passed to the program to determine which framework is in use?

``` json
"precompile": [ "dotnet SpecFlow.NetCore xunit" ]
```

Also, though I haven't used it, looks like [nunit finally supports](https://github.com/nunit/dotnet-test-nunit) Net Core.

**Comment by stajs** [comment]
Right you are, I missed updating that part. Good ideas for future support of the other frameworks, I'll just add a note that they are unsupported at this point in time.

**Comment by smudge202** [comment]
Personally, I'm content with xUnit. But if a tech requirement drives me to one of the other test frameworks I'll see about testing and PR'ing the above changes (if someone doesn't beat me to it).

**Comment by erik-inkapool** [comment]
There's already some work done at https://github.com/geeklearningio/SpecFlow.Dnx, however the diffs there are even less readable than mine have been.

I might be looking into this during the weekend, if I feel like it.

**Comment by stajs** [comment]
#31

**Comment by erik-inkapool** [comment]
We can close this, no?

**Comment by smudge202** [comment]
Just needs a readme update?

> xUnit was the first cab off the rank with support for DNX and then .NET Core. Since then, MsTest and NUnit have become available. Support for these may be added in the future.

**Comment by stajs** [comment]
The README _and_ uploading to nuget.org. Both rectified now.

I haven't added instructions on how to actually change to MsTest; I'm curious to see if any one asks first.
