### ISSUE TITLE
Doesn't honor the NUGET_PACKAGES environment variable

### ISSUE THREAD

**Issue by saarea** [stajs/SpecFlow.NetCore#32]
dotnet core (nuget 3.2+) uses the environment variable NUGET_PACKAGES to identify where to store and read local nuget packages.

Support for both could be really useful - especially on a build server.

**Comment by smudge202** [comment]
Fair one, really easy to implement. If @stajs doesn't beat me to it (and I remember) I'll take a crack later today.

**Comment by stajs** [comment]
Forgive me, I don't understand what the issue is. My best guess at what you are reporting, is that `dotnet restore` doesn't cache packages in the right location? If that is true, it seems a bug in either dotnet CLI or NuGet?

**Comment by erik-inkapool** [comment]
I think he is refering to us incorrectly assuming that nuget packages are located under `userprofile/.nuget` when we are trying to find the specflow executable. See lines 19 and 21 in Fixer.cs https://github.com/stajs/SpecFlow.NetCore/blob/master/src/SpecFlow.NetCore/Fixer.cs#L21

**Comment by stajs** [comment]
Ah, gotcha.

**Comment by saarea** [comment]
Apologies for the lack of clarity here. 

Eric is correct. It is assumed that the path of the specflow exe is in the default location however if the NUGET_PACKAGES environment variable has been set then the location will be different. 

If I get 5 minutes later today I'll create a pull myself if nobody beats to it.

Thanks for the quick responses guys.

**Comment by smudge202** [comment]
[Added a comment](https://github.com/stajs/SpecFlow.NetCore/commit/0560286f6bd9e17f905c570a31b9a2a2e06c55e0#commitcomment-19144358) to the commit about falling through if the path fails, possibly a better option?

**Comment by stajs** [comment]
[I was on the fence about it](https://github.com/stajs/SpecFlow.NetCore/commit/0560286f6bd9e17f905c570a31b9a2a2e06c55e0#commitcomment-19144419).

> The first cut had it falling through, but it felt wrong - I thought if you had the environment variable set, you would want to know it isn't right?

Also added a `--specflow-path` argument in case you don't want to use an environment variable.
