### ISSUE TITLE
How to install specflow for .net core?

### ISSUE THREAD

**Issue by milla** [stajs/SpecFlow.NetCore#33]
I cannot add feature file in .net core project. Do I need to install specifically for .net core?

project.json

```
{
  "version": "1.0.0-*",

  "dependencies": {
    "SpecFlow.NetCore": "1.0.0-rc5",
    "xunit": "2.2.0-beta2-build3300",
    "dotnet-test-xunit": "2.2.0-preview2-build1029"
  },

  "tools": {
    "SpecFlow.NetCore": "1.0.0-rc4"
  },

  "testRunner": "xunit",

  "scripts": {
    "precompile": [ "dotnet SpecFlow.NetCore" ]
  },
  "frameworks": {
    "netcoreapp1.0": {
      "imports": "dnxcore50"
    }
  }
}
```

`

**Comment by erik-inkapool** [comment]
Hey milla!

That config file looks good to me.  To make adding feature files and getting some syntax highlighting you can use the official extension located at https://visualstudiogallery.msdn.microsoft.com/c74211e7-cb6e-4dfa-855d-df0ad4a37dd6

What this tool does is just fixing the build process so the feature files are discoverable by specflow. 

If this didn't solve your problem, can you please expand on the issue you're experiencing?

**Comment by stajs** [comment]
Yes, as @erik-lundgren points out, you'll need the actual Visual Studio tooling he linked.

`SpecFlow.NetCore` is just a kludge/bridge until they add official .NET Core support. which BTW is currently [in progress](https://github.com/techtalk/SpecFlow/pull/649).

**Comment by milla** [comment]
(ah, here is the right place :) )

@SabotageAndi is the release date planned?

I changed project.json to

```
{
  "version": "1.0.0-*",

  "dependencies": {
    //https://github.com/stajs/SpecFlow.NetCore
    "dotnet-test-mstest": "1.1.1-preview",
    "MSTest.TestFramework": "1.0.4-preview",

    "Microsoft.AspNetCore.Razor": "1.0.0",
    "Microsoft.AspNet.Razor": "3.2.3",
    "SpecFlow": "2.1.0",
    "SpecRun.SpecFlow": "1.5.2",
    //"SpecFlow.MsTest": "2.1.0",
    "SpecFlow.xUnit": "2.1.0",
    "Microsoft.VisualStudio.QualityTools.UnitTestFramework": "11.0.50727.1",
    "RazorEngine": "3.9.1",
    "Microsoft.AspNetCore.Mvc": "1.0.1",
    "Microsoft.AspNetCore.Mvc.Formatters.Xml": "1.0.1"
  },
  "testRunner": "mstest",
  "frameworks": {
    "net461": {
      "dependencies": {
      }
    }
  },
  "tools": {
    "SpecFlow.NetCore": "1.0.0-*"
  },
  "scripts": {
    "precompile": [ "dotnet SpecFlow.NetCore" ]
  },
  "commands": {

  },
  "buildOptions": {
    "compile": {
      "Exclude": [
      ]
    }
  }
}
```

but get another error (this could be a bug) that 
Error CS0234 The type or namespace name 'GeneratedTests' does not exist in the namespace 'SpecFlow.GeneratedTests.SpecFlow' (are you missing an assembly reference?)

This is 
`namespace SpecFlow.GeneratedTests.SpecFlow.Features`

I have to remove this every time, and comment out the line in the precompile `SpecFlow.GeneratedTests.SpecFlow.Features.OrderCreateFeature.FeatureSetup(null);`

**Comment by stajs** [comment]
TBH, I think you are still a little confused, @SabotageAndi is unlikely to respond here.

I can't immediately spot the problem with your `project.json`, although you are mixing together xUnit and MSTest dependencies. I recommend seeing if you can build the [sample](https://github.com/stajs/SpecFlow.NetCore/tree/master/samples/) and start from there.

**Comment by omkarachary** [comment]
Is this Issue Fixed from Speckflow Team Is there a Solution for adding new feature with the Vs Templates and Intellisence for the Step Definitions Given When Then and From VS IDE for adding the step Definitions?

We are eagerly waiting for a solution as we are working on a Very big project with arround 10k Speckflow tests

**Comment by stajs** [comment]
I suggest you ask on the SpecFlow repo: https://github.com/techtalk/SpecFlow.

**Comment by SabotageAndi** [comment]
Status and open Tasks for the .NET Core Support is here: https://github.com/techtalk/SpecFlow/projects/2
Help is always welcomed
