### ISSUE TITLE
MsTest doesn't categorize correctly in test explorer for Scenario Outlines

### ISSUE THREAD

**Issue by erik-inkapool** [stajs/SpecFlow.NetCore#34]
MsTest categorizes Scenario Outlines as external, and not of the project in the test explorer. This is because we're not adding `<generator allowDebugGeneratedFiles="true" />` to the `specFlow` section of `app.config`, see https://github.com/techtalk/SpecFlow/issues/275.

**Comment by stajs** [comment]
Thanks!
