### ISSUE TITLE
'test-nunit' returned '-100'.

### ISSUE THREAD

**Issue by ghost** [stajs/SpecFlow.NetCore#37]
Hi guys, I think it's great you are doing this [until TechTalk fixes it](https://github.com/techtalk/SpecFlow/pull/649).  I am trying to port a test project using NUnit over to net core and I think I am close, but I get a test error and it doesn't discover my tests.  Output is:

```
------ Discover test started ------  
Discovering tests in 'C:\Projects\myProj\project.json' ["C:\Program Files\dotnet\dotnet.exe" test "C:\Projects\myProj\project.json" --output "C:\Projects\myProj\bin\Debug\net452\win7-x64" --port 39182 --parentProcessId 8364 --no-build]  
'test-nunit' returned '-100'.  
========== Discover test finished: 0 found (0:00:00.6919996) ==========  
```

project.json is (abridged ... ):  

```
{
    "version": "1.0.0-0",

    "testRunner": "nunit",

    "dependencies": {
        ...
        "SpecFlow": "2.1.0",
        "SpecFlow.NUnit": "2.1.0",
        "SpecFlow.NUnit.Runners": "2.1.0",
        "dotnet-test-nunit": "3.4.0-beta-2",
    },
    "frameworks": {
        "net452": {
            "dependencies": {
                ...
            },
            "frameworkAssemblies": {
                "System.Configuration": "4.0.0.0"
            }
        }
    },
    "runtimes": {
        "win-x64": {}
    },
    "tools": {
        "SpecFlow.NetCore": "1.0.0-rc4"
    },
    "scripts": {
        "precompile": [ "dotnet SpecFlow.NetCore" ]
    }
}
```

**Comment by stajs** [comment]
I can't help with NUnit, but I'll chime in with a few thoughts.

Your `dependencies`:

``` json
"dependencies": {
    "SpecFlow": "2.1.0",
    "SpecFlow.NUnit": "2.1.0",
    "SpecFlow.NUnit.Runners": "2.1.0",
    "dotnet-test-nunit": "3.4.0-beta-2",
},
```

... looks different to the README:

``` json
"dependencies": {
  "NUnit": "3.4.1",
  "dotnet-test-nunit": "3.4.0-beta-2"
},
```

Have you tried dropping the `SpecFlow.NUnit` dependencies and referencing `NUnit` directly?

A quick Google suggests that [`-100` indicates an exception that should be visible on the console](https://groups.google.com/forum/#!topic/nunit-discuss/Wy7MzT1t-18). Have you tried calling NUnit from the command line directly?

[xUnit also can't discover tests from inside Visual Studio](https://github.com/stajs/SpecFlow.NetCore/issues/27#issuecomment-245574470). I wonder if there is a tooling issue.

Another Google shows that people have got [NUnit + Test Explorer working](https://groups.google.com/forum/#!topic/nunit-developer/itwlxytjcWw) with an older version of the runner. Again, they only reference `NUnit` not `SpecFlkow.NUnit` so I would start there.

**Comment by stajs** [comment]
No response.

**Comment by ghost** [comment]
Sorry for the delay, we are finally revisiting this in our project.

Running the nunit-console directly onto our DLL works.  But we don't get to pick our environment related setting this way (appsettings.ENV.json)

It's just running it through the Visual Studio Test Explorer that does not work because VS does not discover the tests.  :(  
Good news is that means it's not you fault, but something with NUnit and Visual Studio.

**Comment by stajs** [comment]
Thanks for the follow up. Yeah, we are all waiting on the tooling to catch up :/

**Comment by ghost** [comment]
Well, [from this thread](https://github.com/nunit/nunit3-vs-adapter/issues/242) it looks like they want to wait for a future release of "dot net test3".
