### ISSUE TITLE
Importing external bindings doesn't seem to work

### ISSUE THREAD

**Issue by erik-am** [stajs/SpecFlow.NetCore#38]
In SpecFlow you can [use bindings from external assemblies](http://www.specflow.org/documentation/Use-Bindings-from-External-Assemblies/)

I'm using this to use import step bindings from a NuGet package. It worked with an old-fashioned .Net 4.6 solution, but not when I use .Net Core and this library.

I added the `<stepAssemblies>` to the `app.config` file that is generated by SpecFlow.NetCore.

**Comment by stajs** [comment]
I don't think this is within my ability to fix. At first I thought it might be [this known issue with the xUnit runner ignoring the config](https://github.com/stajs/SpecFlow.NetCore/issues/27#issuecomment-244596958), but [Brad Wilson said that was only for full .NET Framework, not .NET Core](https://github.com/stajs/SpecFlow.NetCore/issues/27#issuecomment-244629568).

**Comment by erik-am** [comment]
This seems to work as of xunit 2.3.

**Comment by stajs** [comment]
Hooray! Closing this then.
