### ISSUE TITLE
Missing SpecFlow 2.1.0

### ISSUE THREAD

**Issue by georgeonofrei** [stajs/SpecFlow.NetCore#40]
I have the following setup:

>   "dependencies": {
    "SpecFlow": "2.2.0-preview20161020",
    "dotnet-test-mstest": "1.1.2-preview",
    "FluentAssertions": "4.17.0",
    "Microsoft.AspNetCore.TestHost": "1.1.0",
    "MSTest.TestFramework": "1.0.7-preview",
    "Microsoft.AspNet.WebApi.Client": "5.2.2"
  },
  "tools": {
    "SpecFlow.NetCore": "1.0.0-rc7"
  }

I receive the following error:
Can't find SpecFlow: C:\Users\...\\.nuget\packages\SpecFlow\2.1.0\tools\specflow.exe

Is SpecFlow.NetCore 1.0.0-rc7 dependent directly on version 2.1 of SpecFlow?

Thank you, George

**Comment by smudge202** [comment]
That's correct, it currently specifically [requires version 2.1.0](https://github.com/stajs/SpecFlow.NetCore/blob/master/src/SpecFlow.NetCore/Fixer.cs#L36). Bit of a dirty workaround unfortunately. We could probably change the code to look for the latest version of SpecFlow instead; would that work for most people?

**Comment by smudge202** [comment]
Worth noting, you can manually specify the path you want by using `--specflow-path`. I haven't confirmed but I believe you would do this as follows:

```json
"dependencies": {
"SpecFlow": "2.2.0-preview20161020",
"dotnet-test-mstest": "1.1.2-preview",
"FluentAssertions": "4.17.0",
"Microsoft.AspNetCore.TestHost": "1.1.0",
"MSTest.TestFramework": "1.0.7-preview",
"Microsoft.AspNet.WebApi.Client": "5.2.2"
},
"tools": {
"SpecFlow.NetCore": "1.0.0-rc7"
},
"scripts": {
  "precompile": [ "dotnet SpecFlow.NetCore --specflow-path \"C:\\path-to-specflow.exe\"" ]
}
```

I still wonder if we should try to do something more intelligent regarding latest versions; especially given the amount of time it's taking for SpecFlow to get together something that works with core?

**Comment by smudge202** [comment]
If you get bored/have time, @georgeonofrei , feel free to pull down the source for that PR and see if it resolves your issue (without using the above workaround?).

**Comment by georgeonofrei** [comment]
Thanks for the indication. I will keep you posted.

**Comment by stajs** [comment]
@smudge202 Thanks for taking the time to respond to this.

A couple of thoughts about the PR. On the one hand, nice to have something automatic. On the other hand, a different (untested) version of SpecFlow could change it's output, breaking this library so there is a bit of risk there. The command line argument does give you a hook to override if you want to, and it means end users knowingly take on the risk themselves.

Given the latest stable version of SpecFlow is still 2.1.0 and that's the version tested against, I'm more inclined to leave it as is and call out the SpecFlow dependency in the README.

What do you think?

@georgeonofrei Are you actually using a different version to 2.1.0?

**Comment by smudge202** [comment]
@stajs I agree that breaking changes could be brought in by using unsupported versions of SpecFlow, not to mention the alphanumeric nature of the `Max()` version I added is far from ideal (would be better if we pull down the [`semver`](https://github.com/maxhauser/semver) [package](https://www.nuget.org/packages/semver) but not sure you'd want the additional dependency?).

With regards to the override mechanics, my opinion there is that the README is pretty clear right now regarding which version of SpecFlow this package works with. Whilst we provide an override via commandline, personally, I see the act of changing your `project.json` to a greater version (which may end up being stable versions before netcore support arrives in the official SpecFlow repo), should be override enough? i.e. there is already a manual step involved when overriding the specflow version.

We could simply `WriteLine("We've only tested this against v2.1.0 so use v{0} at your own risk.")` ?

**Comment by stajs** [comment]
Yeah, I don't think the additional dependency is warranted at this stage.

The README doesn't currently mention the SpecFlow version at all, perhaps it did at some stage (I can't remember). The sample at least is explicit.

I get the point about updating the SpecFlow version in the `project.json`. I'm still nervous about the potential breaking change, but at least the (additional) command line arg lets you take the risk yourself. I'm wondering if that's enough at this stage. There hasn't been a lot of movement of SpecFlow versions, so might be a moot point. I think they will be waiting for the shift to MsBuild, in which case this will ~probably~ have to be updated again as well (if they haven't got it natively working by then).
