### ISSUE TITLE
This repo is misleading

### ISSUE THREAD

**Issue by gegana** [stajs/SpecFlow.NetCore#45]
It does not support netcoreap1.0 - 1.1, you are still targeting .net framework 4.6.1 hence you should not call this .netcore...

**Comment by stajs** [comment]
.NET Core supports multiple TFMs, and that includes full .NET Framework. In fact, we list [`netcoreapp1.0` as supported](https://github.com/stajs/SpecFlow.NetCore#net-core).

**Comment by jimdeane** [comment]
I've been trying to understand what this means for a couple of days now. My understanding (probably totally wrong) was that i could  use VS2017 to develop a DOTNET CORE class library and then test it using another DOTNET CORE Test Project, using the SpecFlow.NetCore NuGet package (and modifications to the app.config).

The behaviour appears conflicting. 

The .feature.cs gets generated but the Techtalk.Specflow library is missing. 

If I include SpecFlow 2.1.0 the build fails with incompatible .net versions.

Am I simply trying to use this in an impossible way or is there a workaround.

We use Specflow universally and a attempting to start a DOTNET CORE project right now and failing miserable.

Thnaks

**Comment by erik-inkapool** [comment]
I believe it may be the case that we support dotnet core projects, but SpecFlow does not. Perhaps my understanding is flawed though. Us supporting dotnet core doesn't matter if SpecFlow doesn't, of course.

**Comment by jimdeane** [comment]
I created a separate issue for this to be sure I understand what's going on.

**Comment by stajs** [comment]
@gegana  I got caught up on [the technicality of .NET Core and TFMs](https://github.com/stajs/SpecFlow.NetCore/blob/master/src/SpecFlow.NetCore/SpecFlow.NetCore.csproj#L6). We support `netcoreapp1.0` however @erik-lundgren is right, it's a moot point if SpecFlow does not. I should have instead referred you to #39. I'll update the README to clarify.

@jimdeane I'll follow up on #46.
