### ISSUE TITLE
steps in folder are not binding 

### ISSUE THREAD

**Issue by kongres** [stajs/SpecFlow.NetCore#47]
Hi. 
Thank you for the lib. It's good temporary solution for Net Core. 

I have a problem. 
![image](https://cloud.githubusercontent.com/assets/7360716/25652269/04f55cb4-2ff0-11e7-90fd-909d60825424.png)

When I generate step from feature and put them in root of the project. They are detected with no issues and binding is working too:
![image](https://cloud.githubusercontent.com/assets/7360716/25652288/1d19d41e-2ff0-11e7-8997-c76ad67f3d9e.png)

But when I put steps in subfolder they are become invisible for feature file and binding is not working:
![image](https://cloud.githubusercontent.com/assets/7360716/25652317/47d3ceb2-2ff0-11e7-8cde-63b65ab54e6c.png)

Do you have any idea how to fix it? 
I've tried to play with namespaces and tried to add steps cs files to fake.csproj but nothing fixed it.

**Comment by kongres** [comment]
Test project is https://drive.google.com/open?id=0B1nayVKtQZq-WWFqNUVFek1jUGM

**Comment by smudge202** [comment]
The syntax highlighting you're describing isn't handled at all by this tool as far as I know (we simply generate all the `*.cs` behind the `*.feature` files for you). The generated `*.cs` doesn't reference the steps, as you might imagine, instead the `[Binding]` attribute on steps should be scanned by the SpecFlow Visual Studio extension, which is also responsible for the syntax highlighting.

Do the binds actually fail during execution, or just the highlighting? (Outside of netcore it was quite common for highlighting to get confused but projects still be executable).

Looking through the code for the [specflow extension](https://github.com/techtalk/SpecFlow.VisualStudio) the [`ILBindingRegistryBuilder`](https://github.com/techtalk/SpecFlow.VisualStudio/blob/master/IdeIntegration/Bindings/ILBindingRegistryBuilder.cs) _should_ detect the binding if that's the code the extension is using. The [`IdeBindingSourceProcessor`](https://github.com/techtalk/SpecFlow.VisualStudio/blob/master/IdeIntegration/Bindings/IdeBindingSourceProcessor.cs) is less clear however.

If I can find some time I'll try to pull down your project and run it using the extension code (I recommend that being the place to start if you want to take a look at this yourself?).

You could also try raising an issue in the official specflow repos but you'll likely simply get remarks about how this particular repo is not supported by them and full netcore support is WIP. 😞

**Comment by kongres** [comment]
Hi @smudge202 
Thank you for help.
During debugging everything working fine. I can go thought these steps. So the problem is only with highlighting. But it is very hard to work without the binding.

I will try play with the extension. Thank you for getting direction. I've never debugged  extensions for VS. But will try.

I don't think official repo will help in this case. But some strange that nobody report this issue. Maybe reason is in my environment?

**Comment by smudge202** [comment]
I always found that when the syntax highlighting got confused I could simply close/re-open solution/visual studio to give the specflow extension a bit of a kick. It was a nuisance, but did work.

I don't suppose the same is true for you?

**Comment by stajs** [comment]
@smudge202 has summarized accurately. Sorry, it's outside the scope of this project so closing.
