### ISSUE TITLE
dotnet core 2.0 support

### ISSUE THREAD

**Issue by alastairtree** [stajs/SpecFlow.NetCore#48]
This no longer seems to work now that the dotnet test cli has changed for dotnet core 2. Any plans to update it?

**Comment by stajs** [comment]
Not in the short-term, I'll be waiting for my work projects to upgrade to .NET Core 2.0 before I look at this. Hopefully, it's soon but I don't have a timing on that yet. I'm happy to take a PR for it though!

**Comment by kant2002** [comment]
No change in the code is required @stajs for make this work with .NET Core 2.0, you have just package NuGet with .NET Core 2.0 tooling. I submit PR to illustrate it.

**Comment by chrisgbaker** [comment]
@kant2002 Great news that it's a simple change; I spent some time investigating SpecFlow for my .Net Core 2.0 project, and it sounds like it's close.

**Comment by stajs** [comment]
@kant2002 Thanks for the PR! I'll merge it in blind (untested) and circle back to test when my work projects upgrade.

**Comment by stajs** [comment]
Try https://www.nuget.org/packages/SpecFlow.NetCore/1.0.0-rc9. I still haven't had a chance to test it on my work projects yet, but I think it's shaping up thanks to @kant2002. Reopen if it doesn't work.
