### ISSUE TITLE
Do not hardcode to SpecFlow 2.1.0

### ISSUE THREAD

**Issue by skorunka** [stajs/SpecFlow.NetCore#52]
Remove hardcoded SpecFlow version (2.1.0): https://github.com/stajs/SpecFlow.NetCore/blob/a5feb08f41a8d80086d8e2ef8fa1baca3c8ead35/src/SpecFlow.NetCore/Fixer.cs#L40

As a temp fix, copy SpecFlow to yout project folder ie `.\_tools\SpecFlow\` and use this MsBuild task:

`<Exec Command="dotnet SpecFlow.NetCore --specflow-path $(MSBuildThisFileDirectory)_tools\SpecFlow\specflow.exe" />`

**Comment by skorunka** [comment]
Suggestion: introduce a new parameter to specify a SpecFlow version.

**Comment by stajs** [comment]
You can already specify the version (via the path), example see https://github.com/stajs/SpecFlow.NetCore/pull/51. If you use a relative path it will look in your NuGet cache, otherwise you can specify a full path if you have included it directly in your project.
