### ISSUE TITLE
dotnet SpecFlow.NetCore does not work on linux

### ISSUE THREAD

**Issue by estaphorsius** [stajs/SpecFlow.NetCore#53]
Running CLI tool "dotnet SpecFlow.NetCore" fails on Linux (dotnet core 2.0).

Error: value cannot be null (Parameter name: path1)

The command "dotnet SpecFlow.NetCore" exited with code 255.

Shouldn't this also work on linux?

**Comment by stajs** [comment]
I'm afraid not 🙅‍♂️

I've updated the README to hopefully make it clearer:

https://github.com/stajs/SpecFlow.NetCore/blob/master/README.md#supported-frameworks

**Comment by sumantdas** [comment]
so there is no plan to support it on linux, or running in a docker container with base image as microsoft/aspnetcore-build ?

**Comment by stajs** [comment]
Correct, no support for Linux. SpecFlow itself (and by extension this project) is currently limited to Windows platforms with full .NET Framework v4.5.1+. I don't see why Docker with .NET Framework wouldn't work.

**Comment by simonech** [comment]
Hi, has this statement changed since 2018? Now that full .NET Core support has been released? I tried the samples and I was able to run then on a Mac, but cannot find a way to generate the test classes.

**Comment by stajs** [comment]
I'm not using SpecFlow in my (new) day-to-day job so I'm not in a position to update that statement. However a quick Google suggests that [everything is all rosy with the Visual Studio extension now](
https://specflow.org/2019/updating-to-specflow-3/). If someone wants to verify and let me know, I'll be happy to mark this project as deprecated.

**Comment by smudge202** [comment]
Similar situation, I'm not using it day to day anymore but I did research it recently and believe that statement to be true. It's been a good run. :+1:
