### ISSUE TITLE
Scenarios break when the name is too long

### ISSUE THREAD

**Issue by thomasbruggink** [stajs/SpecFlow.NetCore#54]
#The following scenario name demonstrates the problem with long names
`Scenario: This is an example of a case that will fail when the amount of characters in the scenario names goes beyond 80 characters`
When using the original specflow exe to create cs files this results in the following glue code
```
[Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
[Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("This is an example of a case that will fail when the amount of characters in the " +
"scenario names goes beyond 80 characters")]
```
The FixMsTest function uses a regex to remove the Description attribute which results in the following broken glue code
```
[Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]

"scenario names goes beyond 80 characters")]
```
A simple fix is to extend the regex to span multiple lines and remove the Description correctly. Although I don't know why the description has to be removed since it appears to compile just fine.

Anyway I added a pull request to resolve this. # #55

**Comment by stajs** [comment]
Cool, thanks for that!

I'm not using MSTest so I rely on the community to tidy these things up. If you don't think the Description needs to be removed (it seems wrong to me as well) then feel free to patch it with another PR 😄 

@erik-lundgren added support for MSTest (almost a year ago now!) with #31. [There was a reason at the time](31#discussion-diff-77417324), but not sure if it's a good one.
