### ISSUE TITLE
Build fails when there is an existing fake.csproj file (or any extra csproj file)

### ISSUE THREAD

**Issue by freljung** [stajs/SpecFlow.NetCore#57]
If a previous build has failed to clean up the fake.csproj file, new builds will not work, even if the issue that caused the fake.csproj file to remain is fixed.

I had an error in a feature-file, which stopped SpecFlow.NetCore from generating all the x.feature.cs-files but the fake.csproj-file had been generated. Visual Studio displayed
_MSB3073 The command "dotnet SpecFlow.NetCore" exited with code 1._
so it was not apparent what the actual issue was. Once I removed the fake.csproj-file and manually ran dotnet SpecFlow.NetCore I could see the actual cause of the issue.

It's easy to reproduce, just create an empty file next to the csproj for the project running specflow and name _whatever_.csproj.

**Comment by stajs** [comment]
Nice find. I'd take a PR to fix if you want to have a crack at it...

**Comment by freljung** [comment]
Right-o. I'll give it a go. :)

**Comment by freljung** [comment]
Turns out it's dotnet run that fails when the extra csproj-file is present. To work around that I renamed the file-file to just x.fake. For my scenario it worked fine (SpecFlow 2.2.1, NUnit 3.8.1, NUnit3TestAdaper 3.8.0). Hope it helps!

**Comment by stajs** [comment]
👍
