### ISSUE TITLE
.net core 2.0 (CLI)

### ISSUE THREAD

**Issue by AbrahamAlcaina** [stajs/SpecFlow.NetCore#61]
Now we have the 1.0.0 than supports .netcore 2.0
Could you provide me an example of how I can run the test in the CLI?
I'm trying:
```
dotnet ./packages/SpecFlow.NetCore/lib/netcoreapp2.0/dotnet-SpecFlow.NetCore.dll -- --verbose
```
How I can specify the assembly to test?

**Comment by AbrahamAlcaina** [comment]
After read the code I'm using:
```
dotnet ./packages/SpecFlow.NetCore/lib/netcoreapp2.0/dotnet-SpecFlow.NetCore.dll --test-framework xunit --working-directory .\test\myproject.test
```
And works with a c# projects. I'll continue working to make it work with F#

**Comment by stajs** [comment]
I'm glad you figured it out =)
