### ISSUE TITLE
New NuGet package

### ISSUE THREAD

**Issue by zdeneksejcek** [stajs/SpecFlow.NetCore#71]
Hi, would be great to create new NuGet package, at least pre-release, so we can check all the changes on our projects without creating our own NuGets from forks.

Thanks!

**Comment by smudge202** [comment]
I assume this is related to #70 ?

**Comment by stajs** [comment]
Thanks for the reminder!

https://www.nuget.org/packages/SpecFlow.NetCore/1.3.0
