### ISSUE TITLE
Use Project's namespace instead of SpecFlow.GeneratedTests

### ISSUE THREAD

**Issue by ayoung** [stajs/SpecFlow.NetCore#77]
I would like the generated Feature.cs files to be in the namespace of the current project and not the fake SpecFlow.GeneratedTests.

**Comment by stajs** [comment]
Sounds reasonable. I'm happy to take a PR.

**Comment by stajs** [comment]
https://github.com/stajs/SpecFlow.NetCore/issues/85#issuecomment-550567940
