### ISSUE TITLE
Project not rebuilding when changing .feature file in VS 2017 (15.7.1)

### ISSUE THREAD

**Issue by andrebires** [stajs/SpecFlow.NetCore#78]
Hi, after the update to version 15.7.1 of VS 2017, the build task that updates the auto-generated code files is not being called in case of changes in `.feature` files. This seems related to the optimizations done in VS to reduce build time of large projects. The only way to force it to build is if I change a code (`.cs`) file or the project file (`.csproj`).

My solution has 52 projects and if I change only a feature file, the following text is shown in build output window:

`========== Build: 1 succeeded, 0 failed, 52 up-to-date, 0 skipped ==========`

I'm trying to find an workarround for this, but until now I was unable to do. Someone is also experiencing the same issue?

**Comment by stajs** [comment]
I'm sorry to say, I haven't experienced this (yet). Do please let us know if you find out any more on this. Does it work if you `Rebuild` the one project (instead of `Build`)?

**Comment by andrebires** [comment]
The behavior is inconsistent, but it is somehow related to the Test Explorer window. I cleared all caches (VS, temp) and is not ocurring right now. If it happens again, I will comment here. Thanks!

**Comment by andrebires** [comment]
The problem was still occurring and I solved it by putting the following configuration in the test .csproj file:

```xml
<PropertyGroup>
  <DisableFastUpToDateCheck>true</DisableFastUpToDateCheck>
</PropertyGroup>
```
