### ISSUE TITLE
dnx451 samples

### ISSUE THREAD

**Issue by smudge202** [stajs/SpecFlow.NetCore#8]
As per feedback on PR #7, it would be good to get the samples updated to run against the dnx451 work. Samples often suffer from chicken vs egg problems whereby updates to the core library need publishing to nuget before the samples can reference the latest changes.

An alternative approach is mentioned in the comments of PR #7 which I'll give a quick try. Otherwise I guess samples will have to wait until publishing each time.

**Comment by stajs** [comment]
Yeah, you're right about the chicken/egg problem.

**Comment by smudge202** [comment]
The solution presented in #9, which I'll assume should work for you, should work despite chicken vs egg problem. You can test this by incrementing the core library to version 9999 temporarily, run a build on that package, then without doing anything else, change the version in the sample test project to match. So long as you've "produced outputs" on the core library, the NuGet package should be found and pulled in. There is no concept of feed priority as far as I know, so pulling a version down into the sample project from the real NuGet feed can probably only be guaranteed if you clear the src/artifacts folder first.

**Comment by stajs** [comment]
Yeah, great idea (props given in #9) :dancers:
