### ISSUE TITLE
Different result locally and on CI server

### ISSUE THREAD

**Issue by voroninp** [stajs/SpecFlow.NetCore#80]
I have a weird issue. When I run `dotnet build` on CI feature files are not generated due to the error:

> Found mstest in C:\buildAgent\work\67171554868c3343\IntegrationTests\IntegrationTests.csproj
>   Calling: C:\Users\Administrator\.nuget\packages\SpecFlow\2.4.0\tools\specflow.exe generateall "C:\buildAgent\work\67171554868c3343\IntegrationTests\IntegrationTests.csproj.fake" /force /verbose
>   TechTalk.SpecFlow 2.4.0-ci.51+Branch.master.Sha.b0e03e46d1fc3a27a66b3956ea0da2d90b5c4444
>   Copyright c TechTalk 2011
>   ERROR(S):
>   Required option 'p, ProjectFile' is missing.

Whereas locally `-p` option is specified.

> Calling: C:\Users\pavelvoronin\.nuget\packages\specflow\2.4.0\tools\specflow.exe generateall -p "C:\Users\pavelvoronin\Source\Repos\integration.tests.dotnet\IntegrationTests\IntegrationTests.csproj.fake" --force --verbose
>   Processing project: IntegrationTests.csproj

Versions of `specflow.exe` are identical: `2.4.0-ci.51+Branch.master.Sha.b0e03e46d1fc3a27a66b3956ea0da2d90b5c4444`

What may be the reason for this oddity?

**Comment by voroninp** [comment]
```C#
var projectParameterVersion = Version.Parse("2.4.0");
var localSpecFlowVersion = Version.Parse(_specFlowVersion);
if (localSpecFlowVersion >= projectParameterVersion)
    arguments += $@"-p ""{csproj}"" --force --verbose";
else
    arguments += $@"""{csproj}"" /force /verbose";
```

Looks like on the CI server it somehow thinks that version is older.

I found more differences. Locally `_RestoreGraphEntry` task restores `specflow.netcore-netcoreapp2.1-[1.3.3, )` yet on CI it is `specflow.netcore-netcoreapp2.1-[1.2.0, )`

**Comment by voroninp** [comment]
Well, seems TeamCity played a trick with me. It showed me the attempt to build PR, but checked out master, where old `1.2.0` version was specified. =(

**Comment by stajs** [comment]
Damn, hate those ones! Glad you got it figured out =)
