### ISSUE TITLE
Version for package 'Specflow.NetCore' could not be resolved

### ISSUE THREAD

**Issue by chinookproject** [stajs/SpecFlow.NetCore#84]
I have a .NET Core project that I can't build anymore because Specflow.NetCore is giving me a build error.

When I build I get the following error in output:

`Version for package 'SpecFlow.NetCore' could not be resolved.` 

I'm not sure what the problem is. I seem to be the only one having this issue. I did a `git clean -xdf`, but the problem is still there on my machine.

I even tried to specify the version using the `--specflow-version` arg. But that didn't do the trick.

Is there anything else I can try to fix this error?

**Comment by stajs** [comment]
Sounds like a NuGet problem - can you do a package restore?

**Comment by chinookproject** [comment]
I cleared my nuget cache. Even manualy emptied my package folder that is under my 'user' folder. I also tried a `Update-Package -reinstall`. But the problem stays.

Any other ideas?

**Comment by chinookproject** [comment]
I;ve managed to solve this issue.

I tried a lot of things like deleting all my local nuget cache items ([documentation about nuget package cache](https://docs.microsoft.com/en-us/nuget/consume-packages/managing-the-global-packages-and-cache-folders)). Cloning the repo to a new location etc. Nothing worked.

The fix is to do a `dotnet restore` in the folder where to `.csproj` is. For some reason that does something that Visual Studio isn't doing...
