### ISSUE TITLE
Can you please add support for net core 3 

### ISSUE THREAD

**Issue by ssunkari** [stajs/SpecFlow.NetCore#85]
The current version only support net core 2.1.

**Comment by smudge202** [comment]
This project was designed to bridge a gap prior to SpecFlow supporting .Net Core. However, SpecFlow itself now supports .Net Core, so this project is deprecated.

SpecFlow appear to have already added support for .Net Core 3: https://github.com/techtalk/SpecFlow/issues/1678

**Comment by stajs** [comment]
Yes, I think it's time to archive this now that SpecFlow has caught up. Thanks @smudge202 (and every other contributor) for your help!

🍻
